export const fr = {
  title: `Références`,
  contentTab: {
    title: 'Contenu',
    bibliography: [
      `Alliance canadienne de l’épilepsie. (s. d.). À Propos de L’épilepsie. Canadian Epilepsy Alliance. Consulté 10 février 2023, à l’adresse <a href="https://www.canadianepilepsyalliance.org/a-propos-de-lepilepsie/?lang=fr" rel="noreferrer" target="_blank">https://www.canadianepilepsyalliance.org/a-propos-de-lepilepsie/?lang=fr</a>`,
      `Association des personnes épileptiques. (s. d.). Vivre avec l’épilepsie / Épilepsie symptômes / Formation épilepsie | Association des personnes épileptiques. Consulté 10 février 2023, à l’adresse <a href="https://www.arpe02.com/" rel="noreferrer" target="_blank">https://www.arpe02.com/</a>`,
      `Association Épilepsie Gaspésie Sud. (2021, février 8). Page d’accueil—Epilepsie Gaspésie Sud. <a href="https://epilepsiegaspesiesud.com/" rel="noreferrer" target="_blank">https://epilepsiegaspesiesud.com/</a>`,
      `Association québécoise de l’Épilepsie. (s. d.). AQE | Association Québécoise de l’Épilepsie. AQE | Association Québécoise de l’Épilepsie. Consulté 10 février 2023, à l’adresse <a href="https://www.associationquebecoiseepilepsie.com/" rel="noreferrer" target="_blank">https://www.associationquebecoiseepilepsie.com/</a>`,
      `CHU Sainte-Justine. (2017a, mars 17). Conséquences psychologiques : Parlons d’épilepsie. <a href="https://www.chusj.org/fr/soins-services/E/Epilepsie/Parlons-d-epilepsie/Consequences/Psychologiques" rel="noreferrer" target="_blank">https://www.chusj.org/fr/soins-services/E/Epilepsie/Parlons-d-epilepsie/Consequences/Psychologiques</a>`,
      `CHU Sainte-Justine. (2017b, juin 10). L’épilepsie et les risques de décès. <a href="https://www.chusj.org/fr/soins-services/E/Epilepsie/Risques-de-deces" rel="noreferrer" target="_blank">https://www.chusj.org/fr/soins-services/E/Epilepsie/Risques-de-deces</a>`,
      `Desbiens, R., & Savard, M. (2013). Le traitement pharmacologique de l’épilepsie comment s’y retrouver ? Le médecin du Québec, 48(7). <a href="https://lemedecinduquebec.org/Media/120328/031-038DrDesbiens0713.pdf" rel="noreferrer" target="_blank">https://lemedecinduquebec.org/Media/120328/031-038DrDesbiens0713.pdf</a>`,
      `Épilepsie Montérégie. (s. d.). Épilepsie Montérégie Comprendre l’épilepsie, une habitude à cultiver. Épilepsie Montérégie. Consulté 10 février 2023, à l’adresse <a href="https://epilepsiemonteregie.org/" rel="noreferrer" target="_blank">https://epilepsiemonteregie.org/</a>`,
      `Épilepsie section de Québec. (s. d.). Épilepsie Section de Québec – Support et ressources. Consulté 10 février 2023, à l’adresse <a href="https://www.epilepsiequebec.com/" rel="noreferrer" target="_blank">https://www.epilepsiequebec.com/</a>`,
      `Epilepsy Ontario. (s. d.). Epilepsy Ontario – Working Together to Improve Epilepsy Care in Ontario. Consulté 10 février 2023, à l’adresse <a href="https://epilepsyontario.org/" rel="noreferrer" target="_blank">https://epilepsyontario.org/</a>`,
      `Ordres des psychologues du Québec. (s. d.). Accueil | Ordre des Psychologues du Québec—Ordre des psychologues du Québec—OPQ. Ordre des psychologues du Québec. Consulté 10 février 2023, à l’adresse <a href="https://www.ordrepsy.qc.ca" rel="noreferrer" target="_blank">https://www.ordrepsy.qc.ca</a>`,
      `The Center For Epilepsy & Seizure Education In British Columba. (2020, mai 14). Children & Epilepsy | The Center For Epilepsy & Seizure Education In British Columba. <a href="https://esebc.org/children-epilepsy/" rel="noreferrer" target="_blank">https://esebc.org/children-epilepsy/</a>`,
      `Young Epilepsy. (s. d.). Seizure types | Epileptic seizures | Guide for schools. Young Epilepsy. Consulté 10 février 2023, à l’adresse <a href="https://www.youngepilepsy.org.uk/guide-for-schools/epileptic-seizures/seizure-types/" rel="noreferrer" target="_blank">https://www.youngepilepsy.org.uk/guide-for-schools/epileptic-seizures/seizure-types/</a>`,
      `L’épilepsie et les risques de décès [Internet]. [cité 1 mai 2023]. Disponible à l'adresse <a href="h6ps://www.chusj.org/fr/soins-services/E/Epilepsie/Risques-de-deces" rel="noreferrer" target="_blank">h6ps://www.chusj.org/fr/soins-services/E/Epilepsie/Risques-de-deces</a>`,
      `SUDEP [Internet]. Epilepsy Foundation. [cité 1 mai 2023]. Disponible à l'adresse <a href="h6ps://www.epilepsy.com/complica:ons-risks/early-death-sudep" rel="noreferrer" target="_blank">h6ps://www.epilepsy.com/complica:ons-risks/early-death-sudep</a>`
    ]
  },
  imagesTab: {
    title: 'Images',
    bibliography: [
      `<a href="https://www.freepik.com/free-vector/african-family-concept-illustration_27637473.htm#query=family&position=0&from_view=author#position=0&query=family" rel="noreferrer" target="_blank">https://www.freepik.com/free-vector/african-family-concept-illustration_27637473.htm#query=family&position=0&from_view=author#position=0&query=family</a>`,
      `<a href="https://www.freepik.com/free-vector/flat-background-world-mental-health-day_30828184.htm#&position=2&from_view=undefined" rel="noreferrer" target="_blank">https://www.freepik.com/free-vector/flat-background-world-mental-health-day_30828184.htm#&position=2&from_view=undefined</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-cerf-volant-volant_13717697.htm#page=7&query=kid%20flying%20kite&position=48&from_view=keyword&track=ais" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-cerf-volant-volant_13717697.htm#page=7&query=kid%20flying%20kite&position=48&from_view=keyword&track=ais</a>`,
      `<a href="https://www.freepik.com/free-vector/lavender-bouquet-realistic-illustration_3794992.htm#&position=0&from_view=undefined" rel="noreferrer" target="_blank">https://www.freepik.com/free-vector/lavender-bouquet-realistic-illustration_3794992.htm#&position=0&from_view=undefined</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/main-homme-affaires-tenant-point-interrogation-personne-demandant-reponse-aide-soutien-illustration-vectorielle-plane-faq-interrogation-concept-difficulte-pour-banniere-conception-sites-web-page-web-destination_26921528.htm#query=question%20cartoon&position=17&from_view=search&track=ais" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/main-homme-affaires-tenant-point-interrogation-personne-demandant-reponse-aide-soutien-illustration-vectorielle-plane-faq-interrogation-concept-difficulte-pour-banniere-conception-sites-web-page-web-destination_26921528.htm#query=question%20cartoon&position=17&from_view=search&track=ais</a>`,
      `<a href="https://www.freepik.com/free-vector/hand-drawn-flat-design-epilepsy-illustration_22753190.htm" rel="noreferrer" target="_blank">https://www.freepik.com/free-vector/hand-drawn-flat-design-epilepsy-illustration_22753190.htm</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/minuscules-pharmaciens-medicaments-ordonnance-pour-patients-industrie-pharmaceutique-symbole-rx-bouteille-illustration-vectorielle-plate-analgesiques-pharmacie-medecine-concept-sante-pour-banniere_28480885.htm#query=Rx&position=4&from_view=search&track=sph" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/minuscules-pharmaciens-medicaments-ordonnance-pour-patients-industrie-pharmaceutique-symbole-rx-bouteille-illustration-vectorielle-plate-analgesiques-pharmacie-medecine-concept-sante-pour-banniere_28480885.htm#query=Rx&position=4&from_view=search&track=sph</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/robot-operant-patient-chirurgiens-surveillant-travail-bras-robotiques-salle-operation_12291257.htm#query=surgert&position=16&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/robot-operant-patient-chirurgiens-surveillant-travail-bras-robotiques-salle-operation_12291257.htm#query=surgert&position=16&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/robot-operant-patient-chirurgiens-surveillant-travail-bras-robotiques-salle-operation_12291257.htm#query=surgert&position=16&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/robot-operant-patient-chirurgiens-surveillant-travail-bras-robotiques-salle-operation_12291257.htm#query=surgert&position=16&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-epilepsie-design-plat-dessine-main_23162742.htm#query=seizure%20cartoon&position=2&from_view=search&track=ais" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-epilepsie-design-plat-dessine-main_23162742.htm#query=seizure%20cartoon&position=2&from_view=search&track=ais</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/homme-montre-geste-excellente-idee_10541562.htm#query=adult&position=49&from_view=search&track=sph" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/homme-montre-geste-excellente-idee_10541562.htm#query=adult&position=49&from_view=search&track=sph</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-psychologue_8252015.htm#query=psychologie&from_query=psychosocial&position=4&from_view=search&track=sph" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-psychologue_8252015.htm#query=psychologie&from_query=psychosocial&position=4&from_view=search&track=sph</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-architecte-construction_24487811.htm#query=travail&position=3&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-architecte-construction_24487811.htm#query=travail&position=3&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/concept-illustration-amoureuse_6195512.htm#query=amour&position=8&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/concept-illustration-amoureuse_6195512.htm#query=amour&position=8&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-insomnie_10198500.htm#query=sommeil&position=1&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-insomnie_10198500.htm#query=sommeil&position=1&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-cerveau-curiosite_36242174.htm#query=mémoire&position=6&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-cerveau-curiosite_36242174.htm#query=mémoire&position=6&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/concept-illustration-grand-chelem_6193629.htm#query=sports&position=15&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/concept-illustration-grand-chelem_6193629.htm#query=sports&position=15&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-cinema-maison_12068775.htm#query=films&position=3&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-cinema-maison_12068775.htm#query=films&position=3&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-barman-cocktail_20287873.htm#query=alcool&position=3&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-barman-cocktail_20287873.htm#query=alcool&position=3&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-blessure_26388220.htm#query=assurances&position=3&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-blessure_26388220.htm#query=assurances&position=3&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-parents_10933195.htm#query=parents&position=0&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-parents_10933195.htm#query=parents&position=0&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-cinq-enfants_32318749.htm#query=jeune%20enfant&position=18&from_view=keyword&track=ais" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-cinq-enfants_32318749.htm#query=jeune%20enfant&position=18&from_view=keyword&track=ais</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-enseignement_7504540.htm#query=école&position=25&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-enseignement_7504540.htm#query=école&position=25&from_view=author</a>`,
      `<a href="https://fr.freepik.com/vecteurs-libre/illustration-concept-autisme_12831899.htm#query=enfants&position=17&from_view=author" rel="noreferrer" target="_blank">https://fr.freepik.com/vecteurs-libre/illustration-concept-autisme_12831899.htm#query=enfants&position=17&from_view=author</a>`,
      `<a href="https://www.freepik.com/free-vector/hands-holding-signs-with-cross-checkmark-wrong-right-cancel-approved-vote-person-flat-vector-illustration-exam-survey-answer-concept-banner-website-design-landing-web-page_27572576.htm#query=right%20sign&position=16&from_view=keyword&track=ais" rel="noreferrer" target="_blank">https://www.freepik.com/free-vector/hands-holding-signs-with-cross-checkmark-wrong-right-cancel-approved-vote-person-flat-vector-illustration-exam-survey-answer-concept-banner-website-design-landing-web-page_27572576.htm#query=right%20sign&position=16&from_view=keyword&track=ais</a>`
    ]
  }
};
